config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users
  root to: "home#index"
  get 'home/role_privilage' => "home#role_privilage"
  get 'home/user_privilage' => "home#user_privilage"
  get 'home/set_role_permissions' => "home#set_role_permissions"
  get 'home/set_user_permissions' => "home#set_user_permissions"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
  
     
      user ||= User.new # guest user (not logged in)
      # if user.admin?
      #   can :manage, :all
      # elsif user.salesperson?  
      #   can :read, Product
      # elsif user.manager? 
      #   can :create, Product
      #   can :read, Product
      #   can :update, Product
      #   can :destroy, Product
      # end

      if user.access_to_view
        can :read, Product, :user_id 
      elsif
        false
      end

      if user.access_to_add
        can :create, Product , :user_id
      elsif
       false
     end

     if user.access_to_delete
      can :delete, Product , :user_id
     elsif
      false
     end

      if user.access_to_edit
        can :update , Product, :user_id
      elsif
        false
      end


      if user.access_to_view && user.role == "admin"
        can :read, Product, :user_id
      elsif user.access_to_view && user.role == "manager"
        can :read, Product, :user_id
      elsif user.access_to_view && user.role == "salesperson"
        can :read, Product, :user_id
      else
        false
      end

      if user.access_to_add && user.role == "admin"
        can :create, Product, :user_id
      elsif user.access_to_add && user.role == "manager"
        can :create, Product, :user_id
      elsif user.access_to_add && user.role == "salesperson"
        can :create, Product, :user_id
      else
        false
      end

      if user.access_to_delete && user.role == "admin"
        can :destroy, Product, :user_id
      elsif user.access_to_delete && user.role == "manager"
        can :destroy, Product, :user_id
      elsif user.access_to_delete && user.role == "salesperson"
        can :destroy, Product, :user_id
      else
        false
      end

      if user.access_to_edit && user.role == "admin"
        can :update, Product, :user_id
      elsif user.access_to_edit && user.role == "manager"
        can :update, Product, :user_id
      elsif user.access_to_edit && user.role == "salesperson"
        can :update, Product, :user_id
      else
        false
      end
    
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	
	belongs_to :user, optional: true
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :products,dependent: :destroy
         enum role: [:admin, :manager, :salesperson]

    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?


	rescue_from CanCan::AccessDenied do |exception|
		flash[:error] = "Access denied."
		redirect_to root_url
	end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :role ])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

	def role_privilage
	end

	def user_privilage
	end


	def set_user_permissions
		@user = User.find(params[:user_id])
		if params[:action_name] == "view"
			@user.update(access_to_view: params[:access_allowed])
		elsif params[:action_name] == "add"
		    @user.update(access_to_add: params[:access_allowed])
		elsif params[:action_name] == "edit"
			@user.update(access_to_edit: params[:access_allowed])
		elsif params[:action_name] == "delete"
			@user.update(access_to_delete: params[:access_allowed])
		end
        respond_to do |format|
			format.js 
		end 
	end
	
	def set_role_permissions
		@user = User.find(params[:user_id])
		if params[:action_name] == "view"
			@user.update(access_to_view: params[:access_allowed])
		elsif params[:action_name] == "add"
		    @user.update(access_to_add: params[:access_allowed])
		elsif params[:action_name] == "edit"
			@user.update(access_to_edit: params[:access_allowed])
		elsif params[:action_name] == "delete"
			@user.update(access_to_delete: params[:access_allowed])
		end
        respond_to do |format|
			format.js 
		end 
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :image, :description, :price, :ongoing)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/role_privilage.html.slim
.container
  table.table.table-bordered
    tr
      th #
      th View
      th Add
      th Edit
      th Delete
    -User.order(:role).each do |user| 
     tr
      td = user.role 
      td
        -if user.access_to_view 
         input.access_check checked="" data-action-name="view" data-role=( user.role) data-user-id=( user.id) type="checkbox" 
        -else 
         input.access_check data-action-name="view" data-role=( user.role) data-user-id=( user.id ) type="checkbox"
      
      td
        -if user.access_to_add 
         input.access_check checked="" data-action-name="add" data-role=( user.role) data-user-id=( user.id ) type="checkbox" 
        -else 
         input.access_check data-action-name="add" data-role=( user.role) data-user-id=( user.id ) type="checkbox" 
       
      td
        -if user.access_to_edit 
         input.access_check checked="" data-action-name="edit" data-role=( user.role) data-user-id=( user.id ) type="checkbox" 
        -else 
         input.access_check data-action-name="edit" data-role=( user.role) data-user-id=( user.id ) type="checkbox" 
       
      td
       -if user.access_to_delete 
         input.access_check checked="" data-action-name="delete" data-role=( user.role) data-user-id=( user.id ) type="checkbox" 
       -else 
         input.access_check data-action-name="delete" data-role=(user.role) data-user-id=( user.id) type="checkbox" 
        
      

app/views/home/role_privilage.js.erb
window.location.href = '/home/role_privilege';

app/views/home/user_privilage.html.slim
.container
  table.table.table-bordered
    thead
     tr
      th #
      th View
      th Add
      th Edit
      th Delete
    tbody
      -User.order(:first_name).each do |user| 
        tr
          td 
            = user.first_name 
          td
            -if user.access_to_view 
             input.access_check checked="" data-action-name="view" data-user-id=( user.id ) type="checkbox" 
            -else
             input.access_check data-action-name="view" data-user-id=( user.id ) type="checkbox" 
           
          td
            -if user.access_to_add
             input.access_check checked="" data-action-name="add" data-user-id=( user.id ) type="checkbox" 
            -else 
             input.access_check data-action-name="add" data-user-id=( user.id ) type="checkbox" 
            
          td
            -if user.access_to_edit
             input.access_check checked="" data-action-name="edit" data-user-id=( user.id ) type="checkbox" 
            -else 
             input.access_check data-action-name="edit" data-user-id=( user.id) type="checkbox" 

          td
            -if user.access_to_delete 
             input.access_check checked="" data-action-name="delete" data-user-id=( user.id ) type="checkbox" 
            -else 
             input.access_check data-action-name="delete" data-user-id=( user.id) type="checkbox" 
       

app/views/home/user_privilage.js.erb
window.location.href = '/home/user_privilege';

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light
  a.navbar-brand.logo-text href="#"  Amazon-Store
  button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button" 
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item
       = link_to "Home", root_path, class: "nav-link" 
      li.nav-item
       = link_to "Products", products_path, class: "nav-link" 
      li.nav-item
       = link_to "Add Products", new_product_path, class: "nav-link" 
       -if current_user.try(:admin?) 
      li.nav-item
       = link_to "Role Privilage", home_role_privilage_path, class: "nav-link" 
      li.nav-item
       = link_to "User Privilage", home_user_privilage_path, class: "nav-link" 
      
    ul.navbar-nav.my-lg-0
      -if user_signed_in? 
        li
          = link_to('Logout', destroy_user_session_path, class: "btn btn-secondary", method: :delete) 
      -else 
        li
          = link_to "Sign up", new_user_registration_path, class: "btn btn-secondary", :style =>"margin-right:20px" 
        li
          = link_to 'Login', new_user_session_path,class: "btn btn-secondary" ,:style =>"margin-right:20px"
      

app/views/layouts/application.html.slim
doctype html
html
  head
    title AmazonStore
    = csrf_meta_tags 
    = csp_meta_tag 
    
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 
  body
    = render 'layouts/header' 
    = yield 

app/views/products/_form.html.slim
= form_with(model: product, local: true) do |form| 
  -if product.errors.any? 

    h2 = "prohibited this product from being saved:"
    ul
      - product.errors.full_messages.each do |message| 
       li 
         = message 

  .form-group
    = form.label :name 
    = form.text_field :name, class: 'form-control' 
  .form-group
    = form.label :description 
    = form.text_area :description, class: 'form-control' 
  .form-group
    = form.label :price 
    = form.text_field :price, class: 'form-control' 
  .form-group
    = form.label :image 
    br/
    = form.file_field :image 
  .actions
    = form.submit  class: 'btn btn-primary' 

app/views/products/edit.html.slim
.col-md-4.offset-md-4
  .card.mt-5
    h1.card-header Editing Product
    .card-body
      = render 'form', product: @product 
      = link_to 'Show', @product 
      = link_to 'Back', products_path 

app/views/products/index.html.slim
.col-md-8.offset-md-2
  .card.mt-5
    h3.card-header
      Products
    table.table.table-bordered
      thead
        tr
          th Name
          th Description
          th Price
          th Image
          th colspan="3"  Action
      tbody
        -@products.each do |product| 
         tr
           td 
            = product.name 
           td 
            = product.description 
           td 
            = product.price 
           td 
            = product.image 
           td 
            = link_to 'Show', product 
           td 
            = link_to 'Edit', edit_product_path(product) 
           td 
            = link_to 'Destroy', product, method: :delete, data: {confirm: 'Are you sure?'}   
        
    br
  = link_to 'New Product', new_product_path 

app/views/products/new.html.slim
.col-md-4.offset-md-4
  .card.mt-5
    h1.card-header New Product
    .card-body
      = render 'form', product: @product 
      = link_to 'Back', products_path 

app/views/products/show.html.slim
p
  strong Name:
   = @product.name 
p
  strong Description:
   = @product.description 
p
  strong Price:
   = @product.price 
p
  strong Image:
   = image_tag @product.image_url 
   = link_to 'Edit', edit_product_path(@product) 
   = link_to 'Back', products_path 

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>